# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

ppp_docs_config:
  # Current AWS bucket names
  aws_base_path: elife-sciences-aws.com
  articles-bucket: elife-articles

  # bot code
  bot-repo: "https://github.com/elifesciences/elife-bot"
  bot-cron-py: "https://github.com/elifesciences/elife-bot/blob/master/cron.py"
  bot-s3-monitor: "tmp"
  bot-s3-monitor-activity: "tmp"
  bot-publish-poa: "tmp"

  naming-convention: "https://github.com/elifesciences/ppp-project/blob/master/file_naming_spec.md"

  # AWS base config variabels
  ## regions
  region: aws-region
  sqs-region: jr_sqs_region
  simple-db-region: simpledb_region
  ses-region: ses_region
  region-value: us-east-1

  # SimpleDb settings
  simple-db-namespace: simpledb_domain_postfix
  simple-db-namespace-value: "_dev"

  # POA bucket names
  poa-input-bucket: poa_bucket
  poa-input-bucket-value: elife-ejp-poa-delivery-dev

  # Temp POA directories
  tmp-dir-TARGET_OUTPUT_DIR: TARGET_OUTPUT_DIR
  tmp-dir-STAGING_TO_HW_DIR: STAGING_TO_HW_DIR
  tmp-dir-FTP_TO_HW_DIR: FTP_TO_HW_DIR
  tmp-dir-MADE_FTP_READY: MADE_FTP_READY
  tmp-dir-EJP_INPUT_DIR: EJP_INPUT_DIR
  tmp-dir-STAGING_DECAPITATE_PDF_DIR: STAGING_DECAPITATE_PDF_DIR
  tmp-dir-TMP_DIR: TMP_DIR
  tmp-dir-DO_NOT_FTP_TO_HW_DIR: DO_NOT_FTP_TO_HW_DIR
  tmp-dir-XLS_PATH: XLS_PATH

  # SWF buckets and domains
  domain: domain
  domain-value: Publish
  task-list: default_task_list
  task-list-value: DefaultTaskList

  # SQS specific settings
  monitor-queue: jr_S3_monitor_queue
  monitor-queue-value: ppp-test-queue
  monitor-bucket: jr_S3_monitor_bucket
  monitor-bucket-value: ppp-test-source
  eif-output-bucket: jr_S3_NAF_bucket
  eif-output-bucket-value: ppp-test-naf-output

  # Drupal endpoints
  drupal-base-path: "http://dont-have-a-clue-yet.com"
  drupal-eif-path: "/populate"

  #
  # queues and monitors
  # S3_monitor_queue
  # jr_S3_monitor_bucket
  # jr_S3_NAF_bucket   # this is an output bucket



  # PPP config names

  # ppp-monitor-queue:
